language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - yarn
script: 
  - yarn build
deploy:
  provider: surge
  project: ./dist/
  domain: ab-salary.surge.sh  
  skip-cleanup: true
  on:
    branch: master