language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - yarn
script: 
  - yarn build
deploy:
  provider: firebase
  skip-cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: "all-about-salary"
  on:
    branch: master